[project]
name = 'Tokenized-Subscription-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.provider-verification]
path = 'contracts/provider-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.service-level]
path = 'contracts/service-level.clar'
clarity_version = 2
epoch = 2.5

[contracts.subscriber-identity]
path = 'contracts/subscriber-identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-tracking]
path = 'contracts/usage-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
